"""
Tests for the video duration enforcement system.

Tests render_checker_node duration detection and video_duration_fixer_node
time-stretching using synthetic videos generated by ffmpeg.
"""

import os
import subprocess
import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest


def create_test_video(duration_seconds: float, output_path: str) -> bool:
    """Create a silent test video of a specific duration using ffmpeg."""
    cmd = [
        "ffmpeg", "-y",
        "-f", "lavfi", "-i", f"color=c=blue:s=320x240:d={duration_seconds}",
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-an",
        output_path,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    return result.returncode == 0 and Path(output_path).exists()


from src.manim_runner.validator import get_video_duration


@pytest.fixture
def temp_dir():
    d = tempfile.mkdtemp(prefix="test_duration_")
    yield d


class TestRenderCheckerDuration:
    """Tests for duration detection in render_checker_node."""

    def test_detects_duration_mismatch_too_long(self, temp_dir):
        """Video significantly longer than target should be flagged."""
        video_path = os.path.join(temp_dir, "long.mp4")
        assert create_test_video(10.0, video_path), "Failed to create test video"

        # Import locally to avoid neo4j dependency at module level
        import importlib
        import types

        # Mock the problematic imports
        nodes_code = Path("/home/arc/repo/Logomotion/src/agent/nodes.py").read_text()

        state = {
            "rendered_video_path": video_path,
            "scene_length": 0.05,  # 3 seconds target
            "target_duration": 3.0,
        }

        # Use ffprobe directly to verify duration detection works
        actual = get_video_duration(video_path)
        target = 3.0
        ratio = actual / target
        tolerance = 0.20

        assert abs(ratio - 1.0) > tolerance, (
            f"Test setup error: ratio {ratio:.2f} should be outside tolerance"
        )
        assert actual > target, "Video should be longer than target"

    def test_accepts_duration_within_tolerance(self, temp_dir):
        """Video within ±20% of target should pass."""
        video_path = os.path.join(temp_dir, "ok.mp4")
        assert create_test_video(5.0, video_path), "Failed to create test video"

        actual = get_video_duration(video_path)
        target = 5.0
        ratio = actual / target
        tolerance = 0.20

        assert abs(ratio - 1.0) <= tolerance, (
            f"Video should be within tolerance (ratio: {ratio:.2f})"
        )

    def test_detects_duration_mismatch_too_short(self, temp_dir):
        """Video significantly shorter than target should be flagged."""
        video_path = os.path.join(temp_dir, "short.mp4")
        assert create_test_video(2.0, video_path), "Failed to create test video"

        actual = get_video_duration(video_path)
        target = 10.0
        ratio = actual / target
        tolerance = 0.20

        assert abs(ratio - 1.0) > tolerance, (
            f"Test setup error: ratio {ratio:.2f} should be outside tolerance"
        )
        assert actual < target, "Video should be shorter than target"


class TestDurationFixer:
    """Tests for video_duration_fixer_node time-stretching."""

    def test_slows_down_short_video(self, temp_dir):
        """A 3s video targeting 6s should be slowed to ~6s."""
        video_path = os.path.join(temp_dir, "short.mp4")
        assert create_test_video(3.0, video_path), "Failed to create test video"

        actual = get_video_duration(video_path)
        target = 6.0
        factor = actual / target  # 0.5 → need to slow down

        adjusted_path = os.path.join(temp_dir, "adjusted.mp4")
        pts_factor = target / actual  # >1 → slows down video
        cmd = [
            "ffmpeg", "-y",
            "-i", video_path,
            "-filter:v", f"setpts={pts_factor}*PTS",
            "-an",
            adjusted_path,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        assert result.returncode == 0, f"ffmpeg failed: {result.stderr}"
        assert Path(adjusted_path).exists()

        new_duration = get_video_duration(adjusted_path)
        ratio = new_duration / target
        assert abs(ratio - 1.0) <= 0.20, (
            f"Adjusted duration {new_duration:.1f}s should be ~{target:.1f}s (ratio: {ratio:.2f})"
        )

    def test_speeds_up_long_video(self, temp_dir):
        """A 10s video targeting 5s should be sped up to ~5s."""
        video_path = os.path.join(temp_dir, "long.mp4")
        assert create_test_video(10.0, video_path), "Failed to create test video"

        actual = get_video_duration(video_path)
        target = 5.0
        factor = actual / target  # 2.0 → need to speed up

        adjusted_path = os.path.join(temp_dir, "adjusted.mp4")
        pts_factor = target / actual  # <1 → speeds up video
        cmd = [
            "ffmpeg", "-y",
            "-i", video_path,
            "-filter:v", f"setpts={pts_factor}*PTS",
            "-an",
            adjusted_path,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        assert result.returncode == 0, f"ffmpeg failed: {result.stderr}"

        new_duration = get_video_duration(adjusted_path)
        ratio = new_duration / target
        assert abs(ratio - 1.0) <= 0.20, (
            f"Adjusted duration {new_duration:.1f}s should be ~{target:.1f}s (ratio: {ratio:.2f})"
        )

    def test_factor_capped_at_2x(self, temp_dir):
        """Extreme mismatch should be capped at 2x adjustment."""
        actual = 2.0
        target = 100.0
        factor = actual / target  # 0.02

        max_factor = 2.0
        clamped = max(1.0 / max_factor, min(max_factor, factor))
        assert clamped == 1.0 / max_factor, (
            f"Factor {factor} should be clamped to {1.0/max_factor}"
        )


class TestSynchronizerTimestampScaling:
    """Tests for transcript timestamp adjustment in synchronizer_node."""

    def test_scales_timestamps_on_slowdown(self):
        """When video is slowed 2x (speed_ratio=2.0), timestamps should double."""
        sections = [
            {"timestamp": 0.0, "text": "Intro", "audio_path": None},
            {"timestamp": 5.0, "text": "Middle", "audio_path": None},
            {"timestamp": 10.0, "text": "End", "audio_path": None},
        ]
        # speed_ratio = adjusted_dur / original_dur = 2.0 (video now twice as long)
        speed_ratio = 2.0

        adjusted = []
        for s in sections:
            adjusted.append({
                "timestamp": s["timestamp"] * speed_ratio,
                "text": s["text"],
                "audio_path": s.get("audio_path"),
            })

        assert adjusted[0]["timestamp"] == 0.0
        assert adjusted[1]["timestamp"] == 10.0  # 5.0 * 2.0
        assert adjusted[2]["timestamp"] == 20.0  # 10.0 * 2.0

    def test_scales_timestamps_on_speedup(self):
        """When video is sped up 2x (speed_ratio=0.5), timestamps should halve."""
        sections = [
            {"timestamp": 0.0, "text": "Intro", "audio_path": None},
            {"timestamp": 10.0, "text": "Middle", "audio_path": None},
            {"timestamp": 20.0, "text": "End", "audio_path": None},
        ]
        # speed_ratio = adjusted_dur / original_dur = 0.5 (video now half as long)
        speed_ratio = 0.5

        adjusted = []
        for s in sections:
            adjusted.append({
                "timestamp": s["timestamp"] * speed_ratio,
                "text": s["text"],
                "audio_path": s.get("audio_path"),
            })

        assert adjusted[0]["timestamp"] == 0.0
        assert adjusted[1]["timestamp"] == 5.0  # 10.0 * 0.5
        assert adjusted[2]["timestamp"] == 10.0  # 20.0 * 0.5

    def test_no_scaling_when_not_adjusted(self):
        """Timestamps should remain unchanged when no duration adjustment was made."""
        sections = [
            {"timestamp": 0.0, "text": "Intro", "audio_path": None},
            {"timestamp": 5.0, "text": "End", "audio_path": None},
        ]

        # No adjustment → timestamps unchanged
        for s in sections:
            assert s["timestamp"] == s["timestamp"]


class TestShouldFixDuration:
    """Tests for the should_fix_duration conditional edge function logic."""

    def test_routes_to_fixer_when_too_long(self):
        actual = 120.0
        target = 60.0
        factor = actual / target  # 2.0
        assert abs(factor - 1.0) > 0.20

    def test_routes_to_sync_when_ok(self):
        actual = 55.0
        target = 60.0
        factor = actual / target  # 0.917
        assert abs(factor - 1.0) <= 0.20

    def test_routes_to_sync_when_no_duration(self):
        actual = None
        # Missing duration → should skip and go to sync
        assert actual is None
