"""
Tests for the video duration enforcement system.

Tests render_checker_node duration detection, video_duration_fixer_node
time-stretching, synchronizer_node timestamp scaling, and the
should_fix_duration routing function — calling the real implementations
from src.agent.nodes with synthetic videos generated by ffmpeg.
"""

import os
import shutil
import subprocess
import tempfile
from pathlib import Path

import pytest

from src.agent.nodes import (
    render_checker_node,
    video_duration_fixer_node,
    synchronizer_node,
    should_fix_duration,
)
from src.manim_runner.validator import get_video_duration


def create_test_video(duration_seconds: float, output_path: str) -> bool:
    """Create a silent test video of a specific duration using ffmpeg."""
    cmd = [
        "ffmpeg", "-y",
        "-f", "lavfi", "-i", f"color=c=blue:s=320x240:d={duration_seconds}",
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-an",
        output_path,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    return result.returncode == 0 and Path(output_path).exists()


requires_ffmpeg = pytest.mark.skipif(
    shutil.which("ffmpeg") is None, reason="ffmpeg not available"
)


@pytest.fixture
def temp_dir():
    d = tempfile.mkdtemp(prefix="test_duration_")
    yield d
    shutil.rmtree(d, ignore_errors=True)


def _cleanup_temp_dirs(result: dict) -> None:
    """Remove any manim_durfix_ temp dirs returned in a node's result."""
    for d in result.get("temp_dirs") or []:
        shutil.rmtree(d, ignore_errors=True)


class TestRenderCheckerDuration:
    """Tests for duration detection in render_checker_node."""

    @requires_ffmpeg
    def test_detects_duration_mismatch_too_long(self, temp_dir):
        """Video significantly longer than target should be flagged in validation_errors."""
        video_path = os.path.join(temp_dir, "long.mp4")
        assert create_test_video(10.0, video_path), "Failed to create test video"

        result = render_checker_node(
            {"rendered_video_path": video_path, "scene_length": 3.0 / 60, "target_duration": 3.0}
        )

        assert result["actual_duration"] == pytest.approx(10.0, abs=1.0)
        assert result["checked_video_path"] == video_path
        assert any("Duration mismatch" in e for e in result["validation_errors"])
        # Duration mismatch alone does not invalidate the video (by design).
        assert result["video_valid"] is True

    @requires_ffmpeg
    def test_accepts_duration_within_tolerance(self, temp_dir):
        """Video within +/-20% of target should pass with no validation errors."""
        video_path = os.path.join(temp_dir, "ok.mp4")
        assert create_test_video(5.0, video_path), "Failed to create test video"

        result = render_checker_node(
            {"rendered_video_path": video_path, "scene_length": 5.0 / 60, "target_duration": 5.0}
        )

        assert result["video_valid"] is True
        assert result["validation_errors"] == []
        assert result["actual_duration"] == pytest.approx(5.0, abs=1.0)
        assert result["checked_video_path"] == video_path

    @requires_ffmpeg
    def test_detects_duration_mismatch_too_short(self, temp_dir):
        """Video significantly shorter than target should be flagged in validation_errors."""
        video_path = os.path.join(temp_dir, "short.mp4")
        assert create_test_video(2.0, video_path), "Failed to create test video"

        result = render_checker_node(
            {"rendered_video_path": video_path, "scene_length": 10.0 / 60, "target_duration": 10.0}
        )

        assert any("Duration mismatch" in e for e in result["validation_errors"])
        assert result["actual_duration"] == pytest.approx(2.0, abs=1.0)
        # Duration mismatch alone does not invalidate the video (by design).
        assert result["video_valid"] is True

    def test_missing_video_file(self):
        """A path that doesn't exist should be reported as invalid, no ffmpeg required."""
        result = render_checker_node(
            {"rendered_video_path": "/nonexistent/path/video.mp4", "scene_length": 1.0}
        )

        assert result["video_valid"] is False
        assert result["validation_errors"] == ["Video file does not exist"]
        assert result["checked_video_path"] is None
        assert result["actual_duration"] is None

    def test_no_video_path_provided(self):
        """An empty/missing rendered_video_path should also be treated as missing."""
        result = render_checker_node({"scene_length": 1.0})

        assert result["video_valid"] is False
        assert result["validation_errors"] == ["Video file does not exist"]
        assert result["checked_video_path"] is None
        assert result["actual_duration"] is None


class TestDurationFixer:
    """Tests for video_duration_fixer_node time-stretching."""

    @requires_ffmpeg
    def test_slows_down_short_video(self, temp_dir):
        """A 3s video targeting 6s should be slowed to ~6s."""
        video_path = os.path.join(temp_dir, "short.mp4")
        assert create_test_video(3.0, video_path), "Failed to create test video"
        actual = get_video_duration(video_path)

        result = video_duration_fixer_node(
            {"checked_video_path": video_path, "actual_duration": actual, "target_duration": 6.0}
        )
        try:
            assert result["duration_adjusted"] is True
            assert result["duration_factor"] == pytest.approx(2.0, rel=0.2)

            adjusted_path = result["checked_video_path"]
            assert adjusted_path != video_path
            assert Path(adjusted_path).exists()

            new_duration = get_video_duration(adjusted_path)
            assert new_duration == pytest.approx(6.0, rel=0.2)

            assert "temp_dirs" in result and len(result["temp_dirs"]) == 1
            assert Path(result["temp_dirs"][0]).name.startswith("manim_durfix_")
        finally:
            _cleanup_temp_dirs(result)

    @requires_ffmpeg
    def test_speeds_up_long_video(self, temp_dir):
        """A 10s video targeting 5s should be sped up to ~5s."""
        video_path = os.path.join(temp_dir, "long.mp4")
        assert create_test_video(10.0, video_path), "Failed to create test video"
        actual = get_video_duration(video_path)

        result = video_duration_fixer_node(
            {"checked_video_path": video_path, "actual_duration": actual, "target_duration": 5.0}
        )
        try:
            assert result["duration_adjusted"] is True
            assert result["duration_factor"] == pytest.approx(0.5, rel=0.2)

            adjusted_path = result["checked_video_path"]
            new_duration = get_video_duration(adjusted_path)
            assert new_duration == pytest.approx(5.0, rel=0.2)
            assert len(result["temp_dirs"]) == 1
        finally:
            _cleanup_temp_dirs(result)

    def test_within_tolerance_no_adjustment(self):
        """Duration already close to target should skip adjustment entirely (no ffmpeg call)."""
        result = video_duration_fixer_node(
            {"checked_video_path": "/some/video.mp4", "actual_duration": 58.0, "target_duration": 60.0}
        )

        assert result == {"duration_adjusted": False, "duration_factor": None}

    def test_missing_video_path(self):
        result = video_duration_fixer_node(
            {"checked_video_path": None, "actual_duration": 10.0, "target_duration": 5.0}
        )
        assert result == {"duration_adjusted": False, "duration_factor": None}

    def test_missing_actual_duration(self):
        result = video_duration_fixer_node(
            {"checked_video_path": "/some/video.mp4", "actual_duration": None, "target_duration": 5.0}
        )
        assert result == {"duration_adjusted": False, "duration_factor": None}

    def test_invalid_target_duration(self):
        result = video_duration_fixer_node(
            {"checked_video_path": "/some/video.mp4", "actual_duration": 10.0, "target_duration": 0}
        )
        assert result == {"duration_adjusted": False, "duration_factor": None}

    @requires_ffmpeg
    def test_factor_capped_at_2x(self, temp_dir):
        """Extreme mismatch should be capped at 2x adjustment (pts_factor clamped)."""
        video_path = os.path.join(temp_dir, "tiny.mp4")
        assert create_test_video(2.0, video_path), "Failed to create test video"
        actual = get_video_duration(video_path)

        result = video_duration_fixer_node(
            {"checked_video_path": video_path, "actual_duration": actual, "target_duration": 100.0}
        )
        try:
            assert result["duration_adjusted"] is True
            # pts_factor would want to be ~50x, clamped to 2x -> speed_ratio ~2.0
            assert result["duration_factor"] == pytest.approx(2.0, rel=0.2)
        finally:
            _cleanup_temp_dirs(result)


class TestSynchronizerTimestampScaling:
    """Tests for transcript timestamp adjustment in synchronizer_node."""

    def test_scales_timestamps_on_slowdown(self):
        """When video is slowed 2x (duration_factor=2.0), timestamps should double."""
        sections = [
            {"timestamp": 0.0, "text": "Intro", "audio_path": None},
            {"timestamp": 5.0, "text": "Middle", "audio_path": None},
            {"timestamp": 10.0, "text": "End", "audio_path": None},
        ]

        result = synchronizer_node(
            {
                "checked_video_path": "/some/video.mp4",
                "transcript_sections": sections,
                "audio_segments": [],
                "duration_adjusted": True,
                "duration_factor": 2.0,
            }
        )

        adjusted = result["transcript_sections"]
        assert adjusted[0]["timestamp"] == 0.0
        assert adjusted[1]["timestamp"] == 10.0
        assert adjusted[2]["timestamp"] == 20.0
        assert result["synced_video_path"] == "/some/video.mp4"

    def test_scales_timestamps_on_speedup(self):
        """When video is sped up 2x (duration_factor=0.5), timestamps should halve."""
        sections = [
            {"timestamp": 0.0, "text": "Intro", "audio_path": None},
            {"timestamp": 10.0, "text": "Middle", "audio_path": None},
            {"timestamp": 20.0, "text": "End", "audio_path": None},
        ]

        result = synchronizer_node(
            {
                "checked_video_path": "/some/video.mp4",
                "transcript_sections": sections,
                "audio_segments": [],
                "duration_adjusted": True,
                "duration_factor": 0.5,
            }
        )

        adjusted = result["transcript_sections"]
        assert adjusted[0]["timestamp"] == 0.0
        assert adjusted[1]["timestamp"] == 5.0
        assert adjusted[2]["timestamp"] == 10.0

    def test_no_scaling_when_not_adjusted(self):
        """Timestamps should remain unchanged when no duration adjustment was made."""
        sections = [
            {"timestamp": 0.0, "text": "Intro", "audio_path": None},
            {"timestamp": 5.0, "text": "End", "audio_path": None},
        ]

        result = synchronizer_node(
            {
                "checked_video_path": "/some/video.mp4",
                "transcript_sections": sections,
                "audio_segments": [],
                "duration_adjusted": False,
                "duration_factor": None,
            }
        )

        adjusted = result["transcript_sections"]
        assert adjusted[0]["timestamp"] == 0.0
        assert adjusted[1]["timestamp"] == 5.0
        # Unadjusted case returns the original list objects
        assert adjusted == sections

    def test_no_scaling_when_factor_is_one(self):
        """A duration_factor of exactly 1.0 should not rescale timestamps."""
        sections = [{"timestamp": 4.0, "text": "x", "audio_path": None}]

        result = synchronizer_node(
            {
                "checked_video_path": "/some/video.mp4",
                "transcript_sections": sections,
                "audio_segments": [],
                "duration_adjusted": True,
                "duration_factor": 1.0,
            }
        )

        assert result["transcript_sections"][0]["timestamp"] == 4.0


class TestShouldFixDuration:
    """Tests for the should_fix_duration conditional edge function."""

    def test_guide_mode_always_skips_to_synchronizer(self):
        result = should_fix_duration(
            {"duration_mode": "guide", "actual_duration": 120.0, "target_duration": 60.0}
        )
        assert result == "synchronizer"

    def test_strict_mode_routes_to_fixer_when_off(self):
        result = should_fix_duration(
            {"duration_mode": "strict", "actual_duration": 120.0, "target_duration": 60.0}
        )
        assert result == "video_duration_fixer"

    def test_strict_mode_routes_to_sync_when_ok(self):
        result = should_fix_duration(
            {"duration_mode": "strict", "actual_duration": 58.0, "target_duration": 60.0}
        )
        assert result == "synchronizer"

    def test_strict_mode_routes_to_sync_when_duration_missing(self):
        result = should_fix_duration(
            {"duration_mode": "strict", "actual_duration": None, "target_duration": 60.0}
        )
        assert result == "synchronizer"
